import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'favorites_model.freezed.dart';
part 'favorites_model.g.dart';

@freezed
class FavoritesModel with _$FavoritesModel {
  const factory FavoritesModel({
    required String movieId,
    required String userId,
  }) = _FavoritesModel;

  factory FavoritesModel.fromJson(Map<String, Object?> json) =>
      _$FavoritesModelFromJson(json);
}
