import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'trailer_model.freezed.dart';
part 'trailer_model.g.dart';

@freezed
class TrailerModel with _$TrailerModel {
  const factory TrailerModel({
    required String iso_639_1,
    required String iso_3166_1,
    required String name,
    required String key,
    required String site,
    required int size,
    required String type,
    required bool official,
    required String published_at,
    required String id,
  }) = _TrailerModel;

  factory TrailerModel.fromJson(Map<String, Object?> json) =>
      _$TrailerModelFromJson(json);
}
